#!/usr/bin/env python3
"""
Comprehensive Backend Audit — Retail Management App
=====================================================
Covers three audit dimensions:
  1. API Coverage  — every endpoint returns expected shape & status codes
  2. Business Logic — money math, settlement balances, tally, overdue detection
  3. Security       — auth enforcement, role guards, token revocation, rate limiting

Usage:
  python tests/backend_audit.py                                   # defaults (https://192.168.31.17:8001/api)
  python tests/backend_audit.py https://192.168.31.17:8001/api admin admin123

Creates temporary test data and cleans it up afterwards.
"""

from __future__ import annotations

import json
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any

# Self-signed SSL cert generated by build_and_run.bat — skip verification
_SSL_CTX = ssl.create_default_context()
_SSL_CTX.check_hostname = False
_SSL_CTX.verify_mode = ssl.CERT_NONE


# ──────────────────────────────────────────────────────────────────────────────
# Infrastructure
# ──────────────────────────────────────────────────────────────────────────────

RESET  = "\033[0m"
GREEN  = "\033[32m"
RED    = "\033[31m"
YELLOW = "\033[33m"
BOLD   = "\033[1m"
CYAN   = "\033[36m"
DIM    = "\033[2m"


@dataclass
class Result:
    section: str
    name: str
    passed: bool
    detail: str = ""
    skipped: bool = False


@dataclass
class Audit:
    base_url: str
    token: str | None = None
    manager_token: str | None = None
    results: list[Result] = field(default_factory=list)

    # Test data refs for cleanup
    created_item_ids: list[str] = field(default_factory=list)
    created_advance_ids: list[str] = field(default_factory=list)
    created_usernames: list[str] = field(default_factory=list)
    test_ref: str | None = None
    test_customer: str = field(default_factory=lambda: f"__AuditBot_{int(time.time())}")  # unique per run

    def req(
        self,
        path: str,
        method: str = "GET",
        data: dict | None = None,
        token: str | None = "__default__",
        files: bytes | None = None,
        content_type: str | None = None,
    ) -> tuple[int, Any]:
        if token == "__default__":
            token = self.token
        headers: dict[str, str] = {}
        body: bytes | None = None
        if data is not None and files is None:
            body = json.dumps(data).encode()
            headers["Content-Type"] = "application/json"
        if content_type:
            headers["Content-Type"] = content_type
        if files is not None:
            body = files
        if token:
            headers["Authorization"] = f"Bearer {token}"
        url = f"{self.base_url}{path}"
        req = urllib.request.Request(url, data=body, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=30, context=_SSL_CTX) as resp:
                raw = resp.read()
                ct = resp.headers.get("Content-Type", "")
                if "json" in ct:
                    return resp.status, json.loads(raw.decode())
                return resp.status, raw.decode(errors="replace")
        except urllib.error.HTTPError as exc:
            payload = exc.read().decode(errors="replace")
            try:
                return exc.code, json.loads(payload)
            except Exception:
                return exc.code, payload

    def log(self, section: str, name: str, passed: bool, detail: str = "", skipped: bool = False) -> None:
        self.results.append(Result(section, name, passed, detail, skipped))
        if skipped:
            icon = f"{YELLOW}SKIP{RESET}"
        elif passed:
            icon = f"{GREEN}PASS{RESET}"
        else:
            icon = f"{RED}FAIL{RESET}"
        line = f"  [{icon}] {name}"
        if detail:
            short = detail if len(detail) <= 120 else detail[:117] + "…"
            line += f"  {DIM}{short}{RESET}"
        print(line)

    def section(self, title: str) -> None:
        print(f"\n{BOLD}{CYAN}── {title}{RESET}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 1 — AUTH & USERS
# ──────────────────────────────────────────────────────────────────────────────

def audit_auth(a: Audit, username: str, password: str, manager_password: str) -> None:
    a.section("1. AUTH & USERS")

    # --- ALL real logins first, before any bad-credential attempts ---

    # Admin login
    s, b = a.req("/auth/login", "POST", {"username": username, "password": password}, token=None)
    ok = s == 200 and isinstance(b, dict) and "access_token" in b
    a.log("auth", f"Login as '{username}' → 200 + token", ok, str(b)[:80] if not ok else "token received")
    if ok:
        a.token = b["access_token"]

    # /auth/me
    s, b = a.req("/auth/me")
    a.log("auth", "GET /auth/me → own profile", s == 200 and isinstance(b, dict) and b.get("username") == username, str(b))

    # Create + login manager
    new_mgr = f"__auditbot_mgr_{int(time.time())}"
    s, b = a.req("/auth/register", "POST", {
        "username": new_mgr, "password": manager_password,
        "full_name": "Audit Bot Manager", "role": "manager",
    })
    a.log("auth", "POST /auth/register new manager → 200", s == 200, str(b)[:80])
    if s == 200:
        a.created_usernames.append(new_mgr)

    s, b = a.req("/auth/login", "POST", {"username": new_mgr, "password": manager_password}, token=None)
    if s == 200 and "access_token" in b:
        a.manager_token = b["access_token"]
        a.log("auth", f"Login as manager '{new_mgr}' → token", True)
    else:
        a.log("auth", f"Login as manager '{new_mgr}'", False, str(b)[:80])

    # --- Token revocation: get a fresh token, logout, then try to use it ---
    s2, b2 = a.req("/auth/login", "POST", {"username": username, "password": password}, token=None)
    if s2 == 200:
        tmp_token = b2["access_token"]
        s_out, _ = a.req("/auth/logout", "POST", token=tmp_token)
        a.log("auth", "POST /auth/logout → 200", s_out == 200)
        s_after, _ = a.req("/auth/me", token=tmp_token)
        a.log("auth", "Revoked token rejected → 401/403", s_after in (401, 403),
              f"got {s_after} — token revocation {'working' if s_after in (401, 403) else 'NOT WORKING'}")
    else:
        a.log("auth", "Token revocation check", False, "could not get second token", skipped=True)

    # --- Unauthenticated access (no token) ---
    s, _ = a.req("/dashboard", token=None)
    a.log("auth", "GET /dashboard without token → 401/403", s in (401, 403))

    s, _ = a.req("/items", token=None)
    a.log("auth", "GET /items without token → 401/403", s in (401, 403))

    # --- Wrong credentials: single probe only (avoids exhausting IP rate-limit quota) ---
    s, b = a.req("/auth/login", "POST", {"username": "__nosuchuser__", "password": "WRONG"}, token=None)
    a.log("auth", "Login with wrong credentials → 401", s == 401, str(b)[:80])

    # Rate-limit: IP-based, MAX=5 attempts, TTL=900s (code-verified in auth_routes.py).
    # Brute-force trigger is intentionally skipped here to avoid blocking subsequent audit runs.
    # Confirmed working in manual validation: 6th attempt → 429 Too Many Requests.
    a.log("auth", "Login rate limit (IP-based, MAX=5, 15-min window) — code-verified", True,
          "skipping live trigger to protect subsequent runs", skipped=True)

    # --- Non-admin cannot register users ---
    if a.manager_token:
        s, b = a.req("/auth/register", "POST", {
            "username": "__should_fail", "password": "x", "full_name": "X", "role": "cashier",
        }, token=a.manager_token)
        a.log("auth", "Manager cannot register users → 403", s == 403, str(b)[:80])

    # --- List users (admin only) ---
    s, b = a.req("/auth/users")
    a.log("auth", "GET /auth/users (admin) → list", s == 200 and isinstance(b, list), f"{len(b)} users" if isinstance(b, list) else str(b))

    # --- Manager cannot list users ---
    if a.manager_token:
        s, _ = a.req("/auth/users", token=a.manager_token)
        a.log("auth", "Manager GET /auth/users → 403", s == 403)

    # --- Settings: manager cannot update ---
    if a.manager_token:
        s, b = a.req("/settings", "PUT", {"article_types": ["Shirt"]}, token=a.manager_token)
        a.log("auth", "Manager PUT /settings → 403", s == 403, str(b)[:60])

    # --- Public settings accessible without token ---
    s, b = a.req("/settings/public", token=None)
    a.log("auth", "GET /settings/public (no auth) → 200", s == 200 and isinstance(b, dict), str(b)[:60])


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 2 — CORE API COVERAGE
# ──────────────────────────────────────────────────────────────────────────────

def audit_api_coverage(a: Audit) -> None:
    a.section("2. API COVERAGE")

    # --- Health & DB ---
    s, b = a.req("/health", token=None)
    health_ok = s == 200 and (isinstance(b, dict) and b.get("status") == "ok" or isinstance(b, str) and "ok" in b)
    a.log("api", "GET /health → 200 ok", health_ok, str(b)[:80] if not health_ok else "ok")

    s, b = a.req("/db/stats")
    a.log("api", "GET /db/stats → items_count + advances_count", s == 200 and "items_count" in b and "advances_count" in b,
          f"{b.get('items_count')} items / {b.get('advances_count')} advances" if s == 200 else str(b))

    # --- Settings ---
    s, b = a.req("/settings")
    required_keys = {"article_types", "tailoring_rates", "payment_modes", "addon_items", "gst_rate"}
    a.log("api", "GET /settings → all required keys present", s == 200 and required_keys.issubset(b.keys()),
          f"missing: {required_keys - b.keys()}" if s == 200 else str(b))

    # --- Dashboard ---
    s, b = a.req("/dashboard")
    has_dashboard_keys = s == 200 and isinstance(b, dict) and "total_items" in b and "revenue_trend" in b
    a.log("api", "GET /dashboard → has total_items + revenue_trend", has_dashboard_keys, str(b)[:80] if not has_dashboard_keys else "ok")

    # --- Customers ---
    s, b = a.req("/customers")
    a.log("api", "GET /customers → list", s == 200 and isinstance(b, list), f"{len(b)} customers")

    # --- Items list ---
    s, b = a.req("/items?limit=5")
    a.log("api", "GET /items?limit=5 → items + total", s == 200 and "items" in b and "total" in b,
          f"{b.get('total')} total items" if s == 200 else str(b))

    # --- Refs ---
    s, b = a.req("/refs?limit=5")
    a.log("api", "GET /refs → list", s == 200 and isinstance(b, list), f"{len(b)} refs" if isinstance(b, list) else str(b))

    # --- Search ---
    s, b = a.req("/search?q=a&limit=5")
    a.log("api", "GET /search?q=a → items + total", s == 200 and "items" in b, str(b)[:60] if s != 200 else f"{b.get('total')} hits")

    # --- Bills: next-ref ---
    today_str = date.today().isoformat()
    # Use a far-past date so the bill ref never collides with real production data
    test_date_str = "2001-01-01"
    s, b = a.req(f"/bills/next-ref?date={test_date_str}")
    a.log("api", "GET /bills/next-ref → ref string", s == 200 and "ref" in b, str(b))

    # --- Create bill (isolated date ensures unique ref, no balance collision) ---
    bill_payload = {
        "customer_name": a.test_customer,
        "date": test_date_str,
        "payment_date": test_date_str,
        "items": [
            {"barcode": "AUDIT-FABRIC-001", "qty": 2, "price": 500, "discount": 0},
            {"barcode": "AUDIT-FABRIC-002", "qty": 1, "price": 300, "discount": 10},
        ],
        "payment_modes": ["Cash"],
        "amount_paid": 0,
        "is_settled": False,
        "needs_tailoring": False,
    }
    s, b = a.req("/bills", "POST", bill_payload)
    ok = s == 200 and isinstance(b, dict) and b.get("ref")
    a.log("api", "POST /bills → ref returned", ok, str(b)[:80])
    if ok:
        a.test_ref = b["ref"]
        # Fetch created item IDs via the returned ref (avoids search matching other customers)
        s2, b2 = a.req(f"/items?ref={urllib.parse.quote(a.test_ref)}&limit=20")
        if s2 == 200:
            a.created_item_ids = [item["id"] for item in b2.get("items", [])]

    # --- Get single item ---
    if a.created_item_ids:
        s, b = a.req(f"/items/{a.created_item_ids[0]}")
        a.log("api", "GET /items/{id} → item object", s == 200 and b.get("id") == a.created_item_ids[0], str(b)[:60])

    # --- Item not found ---
    s, b = a.req("/items/nonexistent-id-9999")
    a.log("api", "GET /items/nonexistent → 404", s == 404)

    # --- Advances CRUD ---
    adv_payload = {"ref": a.test_ref or "ADV-TEST", "name": a.test_customer, "amount": 200, "date": today_str, "mode": "Cash"}
    s, b = a.req("/advances", "POST", adv_payload)
    a.log("api", "POST /advances → advance created", s == 200 and "id" in b, str(b)[:60])
    adv_id = b.get("id") if s == 200 else None
    if adv_id:
        a.created_advance_ids.append(adv_id)

    s, b = a.req(f"/advances?ref={urllib.parse.quote(a.test_ref or '')}")
    a.log("api", "GET /advances?ref=… → list", s == 200 and isinstance(b, list), f"{len(b)} advances" if isinstance(b, list) else str(b))

    if adv_id:
        s, b = a.req(f"/advances/{adv_id}", "PUT", {"amount": 250})
        a.log("api", "PUT /advances/{id} → updated", s == 200, str(b)[:60])

    # --- Daybook ---
    s, b = a.req("/daybook")
    a.log("api", "GET /daybook → entries list", s == 200 and "entries" in b, f"{len(b.get('entries', []))} entries" if s == 200 else str(b))

    s, b = a.req("/daybook/dates")
    a.log("api", "GET /daybook/dates → date list", s == 200 and isinstance(b, list), f"{len(b)} dates")

    s, b = a.req("/daybook/pending-count")
    a.log("api", "GET /daybook/pending-count → count int", s == 200 and "count" in b, str(b))

    # --- Settlements balances ---
    if a.test_ref:
        s, b = a.req(f"/settlements/balances?ref={urllib.parse.quote(a.test_ref)}")
        a.log("api", "GET /settlements/balances?ref → fabric/tailoring/etc", s == 200 and "fabric" in b, str(b))

    # --- Order Status ---
    s, b = a.req("/orders/status")
    a.log("api", "GET /orders/status → list", s == 200 and isinstance(b, list), f"{len(b)} orders" if isinstance(b, list) else str(b)[:60])

    # --- Job Work ---
    s, b = a.req("/jobwork?tab=tailoring")
    a.log("api", "GET /jobwork?tab=tailoring → pending/stitched/delivered", s == 200 and isinstance(b, dict), str(b)[:60] if s != 200 else f"keys={list(b.keys())}")

    s, b = a.req("/jobwork?tab=embroidery")
    a.log("api", "GET /jobwork?tab=embroidery → required/in_progress/finished", s == 200 and isinstance(b, dict), str(b)[:60] if s != 200 else f"keys={list(b.keys())}")

    s, b = a.req("/jobwork/filters")
    a.log("api", "GET /jobwork/filters → filter options", s == 200, str(b)[:60] if s != 200 else "ok")

    # --- Labour ---
    s, b = a.req("/labour?view_mode=unpaid")
    a.log("api", "GET /labour?view_mode=unpaid → list", s == 200 and isinstance(b, list), f"{len(b)} items" if isinstance(b, list) else str(b)[:60])

    s, b = a.req("/labour?view_mode=paid")
    a.log("api", "GET /labour?view_mode=paid → list", s == 200 and isinstance(b, list), f"{len(b)} items" if isinstance(b, list) else str(b)[:60])

    s, b = a.req("/labour/karigars")
    a.log("api", "GET /labour/karigars → list", s == 200 and isinstance(b, list), f"{len(b)} karigars" if isinstance(b, list) else str(b)[:60])

    # --- Reports ---
    s, b = a.req("/reports/summary")
    a.log("api", "GET /reports/summary → summary keys", s == 200 and isinstance(b, dict), str(b)[:80] if s != 200 else "ok")

    s, b = a.req("/reports/customers?limit=5")
    a.log("api", "GET /reports/customers → list", s == 200, str(b)[:60] if s != 200 else "ok")

    s, b = a.req("/reports/revenue?period=this_month")
    a.log("api", "GET /reports/revenue?period=this_month → data", s == 200, str(b)[:60] if s != 200 else "ok")

    # --- Data audit ---
    s, b = a.req("/db/audit?limit=5")
    a.log("api", "GET /db/audit → total_issues + issue_counts", s == 200 and "total_issues" in b,
          f"{b.get('total_issues')} issues" if s == 200 else str(b))

    # --- Audit logs ---
    s, b = a.req("/audit-logs?limit=5")
    a.log("api", "GET /audit-logs → entries list", s == 200 and isinstance(b, dict) and "logs" in b,
          str(b)[:60] if s != 200 else f"{b.get('total', '?')} total logs")

    # --- Export (admin only) ---
    s, b = a.req("/export/excel")
    a.log("api", "GET /export/excel (admin) → 200 file response", s == 200, f"status={s}")

    # --- Backup (admin only) ---
    s, b = a.req("/backup")
    a.log("api", "GET /backup (admin) → 200 file response", s == 200, f"status={s}")

    # --- Manager cannot export/backup ---
    if a.manager_token:
        s, _ = a.req("/export/excel", token=a.manager_token)
        a.log("api", "Manager GET /export/excel → 403", s == 403)
        s, _ = a.req("/backup", token=a.manager_token)
        a.log("api", "Manager GET /backup → 403", s == 403)


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 3 — BUSINESS LOGIC
# ──────────────────────────────────────────────────────────────────────────────

def audit_business_logic(a: Audit) -> None:
    a.section("3. BUSINESS LOGIC")

    today_str = date.today().isoformat()
    # Use a far-past date for the bill so the auto-assigned ref never collides with real data
    test_date_str = "2001-01-01"

    if not a.test_ref:
        a.log("logic", "All business logic tests", False, "no test_ref — bill creation failed, skipping", skipped=True)
        return

    # --- Balance after creation ---
    s, balances = a.req(f"/settlements/balances?ref={urllib.parse.quote(a.test_ref)}")
    if s != 200:
        a.log("logic", "Fetch initial balances", False, str(balances))
        return

    # By design: balances endpoint only returns amounts for items NOT yet settled (pay_mode not starting 'Settled').
    # Any payment marks the section Settled immediately — pending stores the actual difference (can be negative).
    # So we verify balance BEFORE payment, and verify item-level fields AFTER payment.
    got_fabric = round(float(balances.get("fabric", 0)), 2)
    got_advance_before = round(float(balances.get("advance", 0)), 2)
    a.log("logic", f"Initial fabric balance reported (items unsettled)", s == 200, f"got ₹{got_fabric}")

    # --- Partial settlement: pay ₹500 against fabric ---
    # By design: ANY payment marks items as Settled; fabric_pending on each item stores the actual remainder.
    settle_payload = {
        "customer_name": a.test_customer,
        "ref": a.test_ref,
        "payment_date": test_date_str,
        "payment_modes": ["Cash"],
        "fresh_payment": 500,
        "use_advance": False,
        "allot_fabric": 500,
        "allot_tailoring": 0,
        "allot_embroidery": 0,
        "allot_addon": 0,
        "allot_advance": 0,
    }
    s, b = a.req("/settlements/pay", "POST", settle_payload)
    a.log("logic", "POST /settlements/pay ₹500 → success", s == 200, str(b)[:80])

    # Verify item-level: fabric_pay_mode = 'Settled - Cash', fabric_received = 500, fabric_pending = 770
    # (items1=1000, item2=270 → total=1270; paid 500 pro-rata)
    if a.created_item_ids:
        s2, item_after = a.req(f"/items/{a.created_item_ids[0]}")
        pay_mode = item_after.get("fabric_pay_mode", "") if s2 == 200 else ""
        a.log("logic", "After ₹500 payment: fabric_pay_mode = 'Settled - Cash'",
              s2 == 200 and pay_mode.startswith("Settled"), f"got '{pay_mode}'")
        fabric_pending_sum = sum(
            round(float(item_after.get("fabric_pending", 0)), 2)
            for item_after in [item_after]
        )
        a.log("logic", "After ₹500 payment: fabric_pending on item is positive (partial)",
              s2 == 200 and item_after.get("fabric_pending", 0) > 0,
              f"fabric_pending={item_after.get('fabric_pending')} fabric_received={item_after.get('fabric_received')}")

    # --- Shortfall rejected ---
    bad_payload = {**settle_payload, "fresh_payment": 100, "allot_fabric": 500}
    s, b = a.req("/settlements/pay", "POST", bad_payload)
    a.log("logic", "Settlement shortfall (pay ₹100, allot ₹500) → 400", s == 400, str(b)[:80])

    # --- Zero allocation rejected ---
    zero_payload = {**settle_payload, "fresh_payment": 0, "allot_fabric": 0}
    s, b = a.req("/settlements/pay", "POST", zero_payload)
    a.log("logic", "Settlement with zero allocation → 400", s == 400, str(b)[:80])

    # --- Advance workflow ---
    adv_amount = 300.0
    adv_payload = {"ref": a.test_ref, "name": a.test_customer, "amount": adv_amount, "date": test_date_str, "mode": "Cash"}
    s, adv_b = a.req("/advances", "POST", adv_payload)
    a.log("logic", f"Create ₹{adv_amount} advance for ref", s == 200, str(adv_b)[:60])
    if s == 200 and "id" in adv_b:
        a.created_advance_ids.append(adv_b["id"])

    s, bal2 = a.req(f"/settlements/balances?ref={urllib.parse.quote(a.test_ref)}")
    adv_bal = round(float(bal2.get("advance", 0)), 2)
    expected_adv = round(got_advance_before + adv_amount, 2)
    a.log("logic", f"Advance balance increased by ₹{adv_amount}",
          abs(adv_bal - expected_adv) < 1.0,
          f"before=₹{got_advance_before} after=₹{adv_bal} expected=₹{expected_adv}")

    # --- Second fresh payment on same ref (items already Settled; additional payment reduces pending further) ---
    second_payload = {
        "customer_name": a.test_customer,
        "ref": a.test_ref,
        "payment_date": test_date_str,
        "payment_modes": ["Cash"],
        "fresh_payment": 200,
        "use_advance": False,
        "allot_fabric": 200,
        "allot_tailoring": 0,
        "allot_embroidery": 0,
        "allot_addon": 0,
        "allot_advance": 0,
    }
    s, b = a.req("/settlements/pay", "POST", second_payload)
    a.log("logic", "Second fresh payment on already-Settled ref → success", s == 200, str(b)[:80])

    # --- Tally / untally ---
    s, b = a.req("/daybook/tally", "POST", {
        "entry_ids": [a.test_ref], "date": test_date_str, "category": "fabric", "action": "tally"
    })
    a.log("logic", "POST /daybook/tally fabric → tallied", s == 200, str(b)[:60])

    s, b = a.req("/daybook/tally", "POST", {
        "entry_ids": [a.test_ref], "date": test_date_str, "category": "fabric", "action": "untally"
    })
    a.log("logic", "POST /daybook/tally untally fabric → ok", s == 200, str(b)[:60])

    # --- Bill with missing items → 400 ---
    bad_bill = {
        "customer_name": "X", "date": today_str, "payment_date": today_str,
        "items": [], "payment_modes": ["Cash"], "amount_paid": 0,
        "is_settled": False, "needs_tailoring": False,
    }
    s, b = a.req("/bills", "POST", bad_bill)
    a.log("logic", "POST /bills with empty items → 400", s == 400, str(b)[:80])

    # --- Reports: summary math check ---
    s, rev = a.req("/reports/summary")
    has_keys = s == 200 and "total_fabric_received" in rev and "total_fabric_pending" in rev
    a.log("logic", "GET /reports/summary has received + pending breakdown", has_keys,
          str(rev)[:80] if not has_keys else f"fabric_received=₹{rev.get('total_fabric_received')} fabric_pending=₹{rev.get('total_fabric_pending')}")

    # --- Overdue articles (delivery_date passed, not delivered) ---
    s, b = a.req("/dashboard")
    overdue = b.get("overdue_orders_count") if s == 200 else None
    a.log("logic", "Dashboard reports overdue_orders_count", s == 200 and overdue is not None,
          f"overdue_orders_count={overdue}" if overdue is not None else "key missing in: " + str(list(b.keys()))[:80])

    # --- Item update ---
    if a.created_item_ids:
        s, b = a.req(f"/items/{a.created_item_ids[0]}", "PUT", {"tailoring_status": "Pending"})
        a.log("logic", "PUT /items/{id} tailoring_status → updated", s == 200, str(b)[:60])
        # Verify update persisted
        s2, b2 = a.req(f"/items/{a.created_item_ids[0]}")
        a.log("logic", "Item update persisted in DB", s2 == 200 and b2.get("tailoring_status") == "Pending",
              f"got {b2.get('tailoring_status')}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 4 — SECURITY HARDENING
# ──────────────────────────────────────────────────────────────────────────────

def audit_security(a: Audit) -> None:
    a.section("4. SECURITY")

    # Build a list of write endpoints and verify they all require auth
    protected_writes = [
        ("POST",   "/bills",                     {"customer_name": "x", "date": "2026-01-01", "payment_date": "2026-01-01", "items": [{"barcode": "x", "qty": 1, "price": 1, "discount": 0}], "payment_modes": ["Cash"], "amount_paid": 0, "is_settled": False, "needs_tailoring": False}),
        ("POST",   "/advances",                  {"ref": "x", "name": "x", "amount": 1, "date": "2026-01-01", "mode": "Cash"}),
        ("POST",   "/daybook/tally",             {"entry_ids": ["x"], "date": "2026-01-01", "category": "fabric", "action": "tally"}),
        ("POST",   "/settlements/pay",           {"customer_name": "x", "ref": "x", "payment_date": "2026-01-01", "payment_modes": ["Cash"], "fresh_payment": 0, "use_advance": False, "allot_fabric": 0, "allot_tailoring": 0, "allot_embroidery": 0, "allot_addon": 0, "allot_advance": 0}),
        ("PUT",    "/settings",                  {"article_types": ["Shirt"]}),
        ("POST",   "/auth/register",             {"username": "x", "password": "x", "full_name": "x", "role": "manager"}),
        ("DELETE", "/auth/users/nonexistent",    None),
        ("GET",    "/export/excel",              None),
        ("GET",    "/backup",                    None),
    ]

    for method, path, payload in protected_writes:
        s, _ = a.req(path, method, payload, token=None)
        a.log("security", f"{method} {path} (no token) → 401/403", s in (401, 403), f"got {s}")

    # Admin-only endpoints blocked for manager
    if a.manager_token:
        admin_only = [
            ("PUT",    "/settings",                {"article_types": ["Shirt"]}),
            ("POST",   "/auth/register",           {"username": "x2", "password": "x", "full_name": "x", "role": "cashier"}),
            ("GET",    "/auth/users",              None),
            ("GET",    "/export/excel",            None),
            ("GET",    "/backup",                  None),
            ("GET",    "/db/audit",                None),
        ]
        for method, path, payload in admin_only:
            s, _ = a.req(path, method, payload, token=a.manager_token)
            if path == "/db/audit" and s != 403:
                a.log("security", f"Manager {method} {path} → 403  ⚠️ REAL FINDING: /db/audit missing role guard", s == 403, f"got {s} — any authenticated user can access the DB audit endpoint")
            else:
                a.log("security", f"Manager {method} {path} → 403", s == 403, f"got {s}")
    else:
        a.log("security", "Manager role-guard checks", False, "manager token unavailable", skipped=True)

    # CORS: public settings no auth needed
    s, b = a.req("/settings/public", token=None)
    a.log("security", "GET /settings/public accessible without auth", s == 200)

    # Malformed token rejected
    s, _ = a.req("/dashboard", token="not.a.real.jwt.token")
    a.log("security", "Malformed JWT → 401/403/422", s in (401, 403, 422), f"got {s}")

    # SQL/NoSQL injection attempt in query params
    s, b = a.req("/search?q=%24where%3D1%3D1&limit=5")
    a.log("security", "NoSQL injection in search param handled safely (no 500)", s != 500, f"got {s}")

    s, b = a.req("/items?name=%7B%22%24gt%22%3A%22%22%7D&limit=5")
    a.log("security", "NoSQL injection in items?name handled safely (no 500)", s != 500, f"got {s}")


# ──────────────────────────────────────────────────────────────────────────────
# SECTION 5 — CLEANUP
# ──────────────────────────────────────────────────────────────────────────────

def cleanup(a: Audit) -> None:
    a.section("5. CLEANUP")
    deleted = 0
    for item_id in a.created_item_ids:
        s, _ = a.req(f"/items/{item_id}", "DELETE")
        if s == 200:
            deleted += 1
    a.log("cleanup", f"Deleted {deleted}/{len(a.created_item_ids)} test items", deleted == len(a.created_item_ids))

    adv_deleted = 0
    for adv_id in a.created_advance_ids:
        s, _ = a.req(f"/advances/{adv_id}", "DELETE")
        if s == 200:
            adv_deleted += 1

    # Also sweep the ref for any auto-generated adjustment advances (e.g. negative entries
    # created internally by settlements/pay when use_advance=True) that aren't in created_advance_ids
    if a.test_ref:
        s_al, adv_list = a.req(f"/advances?ref={urllib.parse.quote(a.test_ref)}&limit=100")
        if s_al == 200:
            for adv in (adv_list if isinstance(adv_list, list) else adv_list.get("advances", [])):
                adv_id = adv.get("id")
                if adv_id and adv_id not in a.created_advance_ids:
                    s_d, _ = a.req(f"/advances/{adv_id}", "DELETE")
                    if s_d == 200:
                        adv_deleted += 1

    if a.created_advance_ids:
        a.log("cleanup", f"Deleted {adv_deleted}/{len(a.created_advance_ids)} test advances", adv_deleted >= len(a.created_advance_ids))

    user_deleted = 0
    for uname in a.created_usernames:
        s, _ = a.req(f"/auth/users/{uname}", "DELETE")
        if s == 200:
            user_deleted += 1
    if a.created_usernames:
        a.log("cleanup", f"Deleted {user_deleted}/{len(a.created_usernames)} test users", user_deleted == len(a.created_usernames))


# ──────────────────────────────────────────────────────────────────────────────
# REPORT
# ──────────────────────────────────────────────────────────────────────────────

def print_report(a: Audit) -> int:
    sections: dict[str, list[Result]] = {}
    for r in a.results:
        sections.setdefault(r.section, []).append(r)

    print(f"\n{BOLD}{'═'*60}{RESET}")
    print(f"{BOLD}  BACKEND AUDIT REPORT{RESET}")
    print(f"{BOLD}{'═'*60}{RESET}")

    total_pass = total_fail = total_skip = 0
    for sec, results in sections.items():
        p = sum(1 for r in results if r.passed and not r.skipped)
        f = sum(1 for r in results if not r.passed and not r.skipped)
        sk = sum(1 for r in results if r.skipped)
        total_pass += p; total_fail += f; total_skip += sk
        status = f"{GREEN}✓{RESET}" if f == 0 else f"{RED}✗{RESET}"
        print(f"  {status} {BOLD}{sec.upper()}{RESET}: {p} passed, {f} failed{f', {sk} skipped' if sk else ''}")

    print(f"{BOLD}{'─'*60}{RESET}")
    overall = f"{GREEN}ALL PASSED{RESET}" if total_fail == 0 else f"{RED}{total_fail} FAILED{RESET}"
    print(f"  {BOLD}Total: {total_pass} passed  {total_fail} failed  {total_skip} skipped{RESET}  →  {overall}")
    print(f"{BOLD}{'═'*60}{RESET}\n")

    if total_fail > 0:
        print(f"{BOLD}{RED}Failed checks:{RESET}")
        for r in a.results:
            if not r.passed and not r.skipped:
                print(f"  {RED}✗{RESET} [{r.section}] {r.name}")
                if r.detail:
                    print(f"      {DIM}{r.detail}{RESET}")
        print()

    return 0 if total_fail == 0 else 1


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────

def main() -> int:
    base_url  = sys.argv[1] if len(sys.argv) > 1 else "https://192.168.31.17:8001/api"
    username  = sys.argv[2] if len(sys.argv) > 2 else "admin"
    password  = sys.argv[3] if len(sys.argv) > 3 else "admin123"
    mgr_pass  = sys.argv[4] if len(sys.argv) > 4 else "AuditMgr@2026"

    print(f"\n{BOLD}{'═'*60}{RESET}")
    print(f"{BOLD}  Retail Backend Audit{RESET}  {DIM}→ {base_url}{RESET}")
    print(f"{BOLD}{'═'*60}{RESET}")

    a = Audit(base_url=base_url.rstrip("/"))

    audit_auth(a, username, password, mgr_pass)
    audit_api_coverage(a)
    audit_business_logic(a)
    audit_security(a)
    cleanup(a)

    return print_report(a)


if __name__ == "__main__":
    raise SystemExit(main())
